### ISSUE TITLE
[Osasco] [Tester de Acessibilidade] na NewVegas

### ISSUE THREAD

**Issue by brunopulis** [acessibilidade-brasil/vagas#3]
## Descrição da vaga

Estamos em busca de profissionais com experiência em Teste de Acessibilidade.
A oportunidade é **afirmativa a profissionais com baixa visão ou visão completa**, e atuará em um banco de grande porte!

## Local de trabalho
- 100% Remoto

## Requisitos da vaga

Conhecimento prévio (básico/intermediário/avançado) das ferramentas de acessibilidade:

**Obrigatórios**
- NVDA, JAWS e VIRTUAL VISION;
- Talk Back e VoiceOver;
- Who Can Use.

**Desejáveis**
- conhecimento da WCAG;
- boa capacidade para interpretação de dados;
- ter familiaridade com plataformas desktop e mobile – ambientes do banco;
- conhecimento Intermediário do pacote office;

## Forma de contratação

CLT

## Benefícios da empresa

- Seguro de vida
- VR ou VA
- Assistência médica e odontológica

**Diferenciais**

- Dayoff no dia do seu aniversário

## Range Salarial

A vaga paga entre X.000,00 e X.000,00 reais.

## Sobre a empresa

A New Vegas é uma agência fundamentalmente interativa.

Unimos inteligência, sensibilidade e tecnologia para desenvolver soluções criativas e estratégicas adequadas aos principais desafios dos nossos clientes num mundo complexo e de constantes mudanças políticas, econômicas e culturais.

A New Vegas é membro fundador do Observatório da Diversidade e faz parte do board da Branded Content Marketing Association South America.

### Quem Somos
Somos pessoas que acreditam nas pessoas. Somos extraordinários, somos mentes e corpos inquietos e fluídos, ávidos por desafios e obstinados por transformações. Reimaginamos o mercado da publicidade para que ele seja radicalmente justo e próspero para todos, sem exceções. Acordamos cedo todos os dias para tornar sonhos possíveis.

### O que fazemos
Entre os nossos principais serviços personalizados estão o desenvolvimento de campanhas interativas integradas, planejamento e criação de conteúdo always on em canais digitais, planejamento e relacionamento com influenciadores, pesquisas qualitativas e quantitativas, estudos de relevância e efetividade digital, alocação e manutenção de equipes dedicadas, processos de co-criação, workshops, outsourcing para serviços de comunicação digital, consultoria de comunicação em temas de diversidade.

### Como pensamos
* O desafio de sermos extraordinários supera o de sermos os melhores;
* Que as relações de trabalho com os colaboradores sejam de respeito e não de exaustão;
* Que as relações de negócio com os clientes sejam de crescimento e não de insatisfação;
* Que as relações de parceria com os fornecedores sejam de transparência e não de exploração;
* Que as relações de impacto com a sociedade sejam de transformação e não de apropriação.

Acordamos cedo todos os dias para tornar os sonhos possíveis !

## Como se candidatar

- Por favor envie um email para [danielle.mello@newvegas.com.br](danielle.mello@newvegas.com.br) com seu CV anexado - Enviar no assunto: Vaga do Acessibilidade Brasil
- Candidatar através do site https://newvegas.gupy.io/jobs/1508389

## Labels

- CLT

- Remoto

- São Paulo

**Comment by GabiJusto** [comment]
Essa vaga pode ser para pessoas Deficientes?

**Comment by brunopulis** [comment]
> Essa vaga pode ser para pessoas Deficientes?

Olá @GabiJusto, pela descrição da vaga acredito que sim
